logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(currentTime) | SQL Time: %(executionTime) ms | Category: %(category) | Connection: %(connectionId) | \nSQL: %(sql)

appender=com.p6spy.engine.spy.appender.Slf4JLogger

driverlist=com.mysql.cj.jdbc.Driver
deregisterdrivers=true
dateformat=HH:mm:ss